/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleAlteracao;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author candi
 */
public class AlteracaoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlteracaoUsuario.class.getName());

    /**
     * Creates new form AlteracaoUsuario
     */
    public AlteracaoUsuario(Usuario usuario) {
        initComponents();
        lbl_nome.setText(usuario.getNome());
        c = new ControleAlteracao(this, usuario);
    }

    public JButton getBt_alterar() {
        return bt_alterar;
    }

    public void setBt_alterar(JButton bt_alterar) {
        this.bt_alterar = bt_alterar;
    }

    public JButton getBt_voltarLogin() {
        return bt_voltarLogin;
    }

    public void setBt_voltarLogin(JButton bt_voltarLogin) {
        this.bt_voltarLogin = bt_voltarLogin;
    }

    public JLabel getLbl_senhaNova() {
        return lbl_senhaNova;
    }

    public void setLbl_senhaNova(JLabel lbl_senhaNova) {
        this.lbl_senhaNova = lbl_senhaNova;
    }

    public JTextField getTxt_senhaNova() {
        return txt_senhaNova;
    }

    public void setTxt_senhaNova(JTextField txt_senhaNova) {
        this.txt_senhaNova = txt_senhaNova;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_senhaNova = new javax.swing.JLabel();
        txt_senhaNova = new javax.swing.JTextField();
        bt_alterar = new javax.swing.JButton();
        bt_voltarLogin = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_senhaNova.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_senhaNova.setForeground(new java.awt.Color(0, 0, 255));
        lbl_senhaNova.setText("Informe sua nova senha:");

        bt_alterar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_alterar.setForeground(new java.awt.Color(255, 0, 153));
        bt_alterar.setText("Alterar");
        bt_alterar.addActionListener(this::bt_alterarActionPerformed);

        bt_voltarLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_voltarLogin.setText("Voltar");
        bt_voltarLogin.addActionListener(this::bt_voltarLoginActionPerformed);

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_nome.setText("NOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_voltarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lbl_senhaNova))
                            .addComponent(txt_senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lbl_nome)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbl_senhaNova)
                .addGap(18, 18, 18)
                .addComponent(txt_senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bt_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(bt_voltarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        // TODO add your handling code here:
        c.atualizar();
    }//GEN-LAST:event_bt_alterarActionPerformed

    private void bt_voltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bt_voltarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AlteracaoUsuario().setVisible(true));
//    }

    
    private ControleAlteracao c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_voltarLogin;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senhaNova;
    private javax.swing.JTextField txt_senhaNova;
    // End of variables declaration//GEN-END:variables
}
