/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleBuscar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Usuario;
import controller.ControleBuscar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;

/**
 *
 * @author candi
 */
public class BuscarVideo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscarVideo.class.getName());
    /**
     * Creates new form BuscarVideo
     */
    
    
    public BuscarVideo(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null); //aparece no meio
        getContentPane().setBackground(new java.awt.Color(216, 181, 230)); // Mudar cor

        this.c = new ControleBuscar(this);
    }
    

    public ControleBuscar getC() {
        return c;
    }

    public void setC(ControleBuscar c) {
        this.c = c;
    }

    public JButton getBt_buscar() {
        return bt_buscar;
    }

    public void setBt_buscar(JButton bt_buscar) {
        this.bt_buscar = bt_buscar;
    }

    public JButton getBt_voltar() {
        return bt_voltar;
    }

    public void setBt_voltar(JButton bt_voltar) {
        this.bt_voltar = bt_voltar;
    }


    public JLabel getLbl_buscar() {
        return lbl_buscar;
    }

    public void setLbl_buscar(JLabel lbl_buscar) {
        this.lbl_buscar = lbl_buscar;
    }

    public JLabel getLbl_buscar1() {
        return lbl_buscar1;
    }

    public void setLbl_buscar1(JLabel lbl_buscar1) {
        this.lbl_buscar1 = lbl_buscar1;
    }

    public JLabel getLbl_classificacao() {
        return lbl_classificacao;
    }

    public void setLbl_classificacao(JLabel lbl_classificacao) {
        this.lbl_classificacao = lbl_classificacao;
    }

    public JLabel getLbl_genero() {
        return lbl_genero;
    }

    public void setLbl_genero(JLabel lbl_genero) {
        this.lbl_genero = lbl_genero;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }



    public JTextArea getTxtA_Sinopse() {
        return txtA_Sinopse;
    }

    public void setTxtA_Sinopse(JTextArea txtA_Sinopse) {
        this.txtA_Sinopse = txtA_Sinopse;
    }

    

    public JTextField getTxt_buscar() {
        return txt_buscar;
    }

    public void setTxt_buscar(JTextField txt_buscar) {
        this.txt_buscar = txt_buscar;
    }

    public JLabel getLbl_infos() {
        return lbl_infos;
    }

    public void setLbl_infos(JLabel lbl_infos) {
        this.lbl_infos = lbl_infos;
    }



    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_buscar = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        lbl_classificacao = new javax.swing.JLabel();
        bt_buscar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        bt_voltar = new javax.swing.JButton();
        lbl_buscar1 = new javax.swing.JLabel();
        lbl_infos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_Sinopse = new javax.swing.JTextArea();
        lbl_buscar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Vídeos");
        setBackground(new java.awt.Color(204, 204, 204));

        lbl_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_buscar.setForeground(new java.awt.Color(102, 0, 102));
        lbl_buscar.setText("Digite o nome do vídeo que deseja buscar:");

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nome.setText(" ");

        lbl_genero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_genero.setText(" ");

        lbl_classificacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_classificacao.setText(" ");

        bt_buscar.setBackground(new java.awt.Color(102, 0, 102));
        bt_buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_buscar.setForeground(new java.awt.Color(255, 255, 255));
        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(this::bt_buscarActionPerformed);

        txt_buscar.addActionListener(this::txt_buscarActionPerformed);

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_voltar.setForeground(new java.awt.Color(102, 0, 102));
        bt_voltar.setText("Voltar");
        bt_voltar.addActionListener(this::bt_voltarActionPerformed);

        lbl_buscar1.setForeground(new java.awt.Color(102, 0, 102));
        lbl_buscar1.setText("As informações do vídeo irão aparecer abaixo");

        lbl_infos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_infos.setText(" ");

        txtA_Sinopse.setColumns(20);
        txtA_Sinopse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtA_Sinopse.setRows(5);
        jScrollPane1.setViewportView(txtA_Sinopse);

        lbl_buscar2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbl_buscar2.setForeground(new java.awt.Color(102, 0, 102));
        lbl_buscar2.setText("Encontre seus filmes e séries favoritos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_classificacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_infos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_buscar1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_buscar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                            .addComponent(bt_buscar)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lbl_buscar2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lbl_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lbl_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbl_classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_infos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        // TODO add your handling code here:
        c.acaoPesquisar();
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new BuscarVideo().setVisible(true));
//    }
    
    private ControleBuscar c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_buscar1;
    private javax.swing.JLabel lbl_buscar2;
    private javax.swing.JLabel lbl_classificacao;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_infos;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JTextArea txtA_Sinopse;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
