/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import controller.ControleCriarLista;
import model.Usuario;

/**
 *
 * @author candi
 */
public class CriarLista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarLista.class.getName());

    /**
     * Creates new form CriarLista
     */
    public CriarLista(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.c = new ControleCriarLista(this, usuario);
    }

    public JButton getBt_criarLista() {
        return bt_criarLista;
    }

    public void setBt_criarLista(JButton bt_criarLista) {
        this.bt_criarLista = bt_criarLista;
    }

    public JButton getBt_voltar() {
        return bt_voltar;
    }

    public void setBt_voltar(JButton bt_voltar) {
        this.bt_voltar = bt_voltar;
    }

    public JLabel getLbl_criarLista() {
        return lbl_criarLista;
    }

    public void setLbl_criarLista(JLabel lbl_criarLista) {
        this.lbl_criarLista = lbl_criarLista;
    }

    public JLabel getLbl_descricaoLista() {
        return lbl_descricaoLista;
    }

    public void setLbl_descricaoLista(JLabel lbl_descricaoLista) {
        this.lbl_descricaoLista = lbl_descricaoLista;
    }

    public JLabel getLbl_nomeLista() {
        return lbl_nomeLista;
    }

    public void setLbl_nomeLista(JLabel lbl_nomeLista) {
        this.lbl_nomeLista = lbl_nomeLista;
    }

    public JTextField getTxt_descricaoLista() {
        return txt_descricaoLista;
    }

    public void setTxt_descricaoLista(JTextField txt_descricaoLista) {
        this.txt_descricaoLista = txt_descricaoLista;
    }

    public JTextField getTxt_nomeLista() {
        return txt_nomeLista;
    }

    public void setTxt_nomeLista(JTextField txt_nomeLista) {
        this.txt_nomeLista = txt_nomeLista;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_criarLista = new javax.swing.JLabel();
        txt_nomeLista = new javax.swing.JTextField();
        lbl_nomeLista = new javax.swing.JLabel();
        txt_descricaoLista = new javax.swing.JTextField();
        lbl_descricaoLista = new javax.swing.JLabel();
        bt_criarLista = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_criarLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_criarLista.setForeground(new java.awt.Color(255, 0, 102));
        lbl_criarLista.setText("Insira as informações abaixo para criar a lista:");

        lbl_nomeLista.setForeground(new java.awt.Color(0, 0, 255));
        lbl_nomeLista.setText("Adicione o nome da lista:");

        lbl_descricaoLista.setForeground(new java.awt.Color(0, 0, 255));
        lbl_descricaoLista.setText("Adicione uma descrição:");

        bt_criarLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_criarLista.setText("Criar Lista");
        bt_criarLista.addActionListener(this::bt_criarListaActionPerformed);

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_voltar.setText("Voltar");
        bt_voltar.addActionListener(this::bt_voltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbl_criarLista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nomeLista)
                            .addComponent(txt_nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_descricaoLista)
                            .addComponent(txt_descricaoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(bt_criarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_criarLista)
                .addGap(57, 57, 57)
                .addComponent(lbl_nomeLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lbl_descricaoLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descricaoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(bt_criarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_criarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criarListaActionPerformed
        // TODO add your handling code here:
        c.criarLista();
    }//GEN-LAST:event_bt_criarListaActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_bt_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CriarLista().setVisible(true));
//    }

    private ControleCriarLista c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_criarLista;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel lbl_criarLista;
    private javax.swing.JLabel lbl_descricaoLista;
    private javax.swing.JLabel lbl_nomeLista;
    private javax.swing.JTextField txt_descricaoLista;
    private javax.swing.JTextField txt_nomeLista;
    // End of variables declaration//GEN-END:variables
}
