/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleExclusao;
import javax.swing.JButton;
import javax.swing.JLabel;
import model.Usuario;

/**
 *
 * @author candi
 */
public class ExclusaoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExclusaoUsuario.class.getName());

    /**
     * Creates new form ExclusaoUsuario
     */
    public ExclusaoUsuario(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null); //aparece no meio

        lbl_nome.setText(usuario.getNome());
        c = new ControleExclusao(this, usuario);
    }

    public JButton getBt_excluirPerfil() {
        return bt_excluirPerfil;
    }

    public void setBt_excluirPerfil(JButton bt_excluirPerfil) {
        this.bt_excluirPerfil = bt_excluirPerfil;
    }

    public JButton getBt_voltarLogado() {
        return bt_voltarLogado;
    }

    public void setBt_voltarLogado(JButton bt_voltarLogado) {
        this.bt_voltarLogado = bt_voltarLogado;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }

    public JLabel getLbl_pgtExcluir() {
        return lbl_pgtExcluir;
    }

    public void setLbl_pgtExcluir(JLabel lbl_pgtExcluir) {
        this.lbl_pgtExcluir = lbl_pgtExcluir;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        lbl_pgtExcluir = new javax.swing.JLabel();
        bt_excluirPerfil = new javax.swing.JButton();
        bt_voltarLogado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_nome.setText("NOME");

        lbl_pgtExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_pgtExcluir.setForeground(new java.awt.Color(0, 0, 255));
        lbl_pgtExcluir.setText("Deseja realmente excluir o seu cadastro?");

        bt_excluirPerfil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_excluirPerfil.setText("Excluir");
        bt_excluirPerfil.addActionListener(this::bt_excluirPerfilActionPerformed);

        bt_voltarLogado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_voltarLogado.setText("Voltar");
        bt_voltarLogado.addActionListener(this::bt_voltarLogadoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbl_pgtExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_voltarLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_excluirPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lbl_nome)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbl_pgtExcluir)
                .addGap(39, 39, 39)
                .addComponent(bt_excluirPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bt_voltarLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_excluirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirPerfilActionPerformed
        // TODO add your handling code here:
        c.remover();
    }//GEN-LAST:event_bt_excluirPerfilActionPerformed

    private void bt_voltarLogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarLogadoActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bt_voltarLogadoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ExclusaoUsuario().setVisible(true));
//    }
//
    private ControleExclusao c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excluirPerfil;
    private javax.swing.JButton bt_voltarLogado;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_pgtExcluir;
    // End of variables declaration//GEN-END:variables
}
