/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleExcluirLista;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author candi
 */
public class TelaExcluirLista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExcluirLista.class.getName());

    private Usuario usuario;
    /**
     * Creates new form TelaDeletarLista
     */
    public TelaExcluirLista(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        c = new ControleExcluirLista(this, usuario);
    }

    public JButton getBt_deletarLista() {
        return bt_deletarLista;
    }

    public void setBt_deletarLista(JButton bt_deletarLista) {
        this.bt_deletarLista = bt_deletarLista;
    }

    public JButton getBt_voltarLista() {
        return bt_voltarLista;
    }

    public void setBt_voltarLista(JButton bt_voltarLista) {
        this.bt_voltarLista = bt_voltarLista;
    }

    public JLabel getLbl_nomeListaExcluir() {
        return lbl_nomeListaExcluir;
    }

    public void setLbl_nomeListaExcluir(JLabel lbl_nomeListaExcluir) {
        this.lbl_nomeListaExcluir = lbl_nomeListaExcluir;
    }

    public JTextField getTxt_listaExcluir() {
        return txt_listaExcluir;
    }

    public void setTxt_listaExcluir(JTextField txt_listaExcluir) {
        this.txt_listaExcluir = txt_listaExcluir;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nomeListaExcluir = new javax.swing.JLabel();
        txt_listaExcluir = new javax.swing.JTextField();
        bt_deletarLista = new javax.swing.JButton();
        bt_voltarLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nomeListaExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nomeListaExcluir.setForeground(new java.awt.Color(51, 0, 255));
        lbl_nomeListaExcluir.setText("Insira o nome da lista que você deseja excluir:");

        bt_deletarLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_deletarLista.setForeground(new java.awt.Color(255, 0, 51));
        bt_deletarLista.setText("Deletar Lista");
        bt_deletarLista.addActionListener(this::bt_deletarListaActionPerformed);

        bt_voltarLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_voltarLista.setText("Voltar");
        bt_voltarLista.addActionListener(this::bt_voltarListaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nomeListaExcluir)
                            .addComponent(txt_listaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_voltarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_deletarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lbl_nomeListaExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_listaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(bt_deletarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bt_voltarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deletarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarListaActionPerformed
        // TODO add your handling code here:
        c.excluirLista();
    }//GEN-LAST:event_bt_deletarListaActionPerformed

    private void bt_voltarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarListaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_voltarListaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new TelaDeletarLista().setVisible(true));
//    }
//
    private ControleExcluirLista c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deletarLista;
    private javax.swing.JButton bt_voltarLista;
    private javax.swing.JLabel lbl_nomeListaExcluir;
    private javax.swing.JTextField txt_listaExcluir;
    // End of variables declaration//GEN-END:variables
}
