/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleExcluirLista;
import controller.ControleGerenciarListas;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author candi
 */
public class TelaGerenciarListas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaGerenciarListas.class.getName());
    private Usuario usuario;
    /**
     * Creates new form TelaGerenciarListas
     */
    public TelaGerenciarListas(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        c = new ControleGerenciarListas(this, usuario);
    }

    public JButton getBt_adicionar() {
        return bt_adicionar;
    }

    public void setBt_adicionar(JButton bt_adicionar) {
        this.bt_adicionar = bt_adicionar;
    }

    public JButton getBt_buscarVideo() {
        return bt_buscarVideo;
    }

    public void setBt_buscarVideo(JButton bt_buscarVideo) {
        this.bt_buscarVideo = bt_buscarVideo;
    }

    public JButton getBt_remover() {
        return bt_remover;
    }

    public void setBt_remover(JButton bt_remover) {
        this.bt_remover = bt_remover;
    }

    public JLabel getLbl_classificacao() {
        return lbl_classificacao;
    }

    public void setLbl_classificacao(JLabel lbl_classificacao) {
        this.lbl_classificacao = lbl_classificacao;
    }

    public JLabel getLbl_escolhaLista() {
        return lbl_escolhaLista;
    }

    public void setLbl_escolhaLista(JLabel lbl_escolhaLista) {
        this.lbl_escolhaLista = lbl_escolhaLista;
    }

    public JLabel getLbl_escolhaLista1() {
        return lbl_escolhaLista1;
    }

    public void setLbl_escolhaLista1(JLabel lbl_escolhaLista1) {
        this.lbl_escolhaLista1 = lbl_escolhaLista1;
    }

    public JLabel getLbl_genero() {
        return lbl_genero;
    }

    public void setLbl_genero(JLabel lbl_genero) {
        this.lbl_genero = lbl_genero;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }

    public JLabel getLbl_resultado() {
        return lbl_resultado;
    }

    public void setLbl_resultado(JLabel lbl_resultado) {
        this.lbl_resultado = lbl_resultado;
    }

    public JTextField getTxt_nomeLista() {
        return txt_nomeLista;
    }

    public void setTxt_nomeLista(JTextField txt_nomeLista) {
        this.txt_nomeLista = txt_nomeLista;
    }

    public JTextField getTxt_nomeVideo() {
        return txt_nomeVideo;
    }

    public void setTxt_nomeVideo(JTextField txt_nomeVideo) {
        this.txt_nomeVideo = txt_nomeVideo;
    }

    public JButton getBt_voltar() {
        return bt_voltar;
    }

    public void setBt_voltar(JButton bt_voltar) {
        this.bt_voltar = bt_voltar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_escolhaLista = new javax.swing.JLabel();
        txt_nomeLista = new javax.swing.JTextField();
        lbl_escolhaLista1 = new javax.swing.JLabel();
        txt_nomeVideo = new javax.swing.JTextField();
        bt_buscarVideo = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        lbl_classificacao = new javax.swing.JLabel();
        bt_adicionar = new javax.swing.JButton();
        bt_remover = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adicionar/remover vídeos da lista");

        lbl_escolhaLista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_escolhaLista.setForeground(new java.awt.Color(51, 0, 255));
        lbl_escolhaLista.setText("Escolha a lista que deseja adicionar ou remover o vídeo:");

        lbl_escolhaLista1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_escolhaLista1.setForeground(new java.awt.Color(51, 0, 255));
        lbl_escolhaLista1.setText("Digite o nome do vídeo que deseja adicionar:");

        bt_buscarVideo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarVideo.setText("Buscar");
        bt_buscarVideo.addActionListener(this::bt_buscarVideoActionPerformed);

        lbl_resultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_resultado.setText("Resultado:");

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nome.setText("Nome: ");

        lbl_genero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_genero.setText("Gênero:");

        lbl_classificacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_classificacao.setText("Classificação:");

        bt_adicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_adicionar.setText("Adicionar");
        bt_adicionar.addActionListener(this::bt_adicionarActionPerformed);

        bt_remover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_remover.setText("Remover");
        bt_remover.addActionListener(this::bt_removerActionPerformed);

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_voltar.setText("Voltar");
        bt_voltar.addActionListener(this::bt_voltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_classificacao)
                            .addComponent(lbl_genero)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_escolhaLista1)
                            .addComponent(txt_nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_escolhaLista)
                            .addComponent(lbl_resultado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_nomeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_buscarVideo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lbl_escolhaLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl_escolhaLista1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_buscarVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nomeVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_classificacao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarVideoActionPerformed
        // TODO add your handling code here:
        c.buscarVideo();
    }//GEN-LAST:event_bt_buscarVideoActionPerformed

    private void bt_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarActionPerformed
        // TODO add your handling code here:
        c.adicionarVideoNaLista();
    }//GEN-LAST:event_bt_adicionarActionPerformed

    private void bt_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerActionPerformed
        // TODO add your handling code here:
        c.removerVideoDaLista();
    }//GEN-LAST:event_bt_removerActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_voltarActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new TelaGerenciarListas().setVisible(true));
//    }
//
    
    private ControleGerenciarListas c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JButton bt_buscarVideo;
    private javax.swing.JButton bt_remover;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel lbl_classificacao;
    private javax.swing.JLabel lbl_escolhaLista;
    private javax.swing.JLabel lbl_escolhaLista1;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_nomeLista;
    private javax.swing.JTextField txt_nomeVideo;
    // End of variables declaration//GEN-END:variables
}
