/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Usuario;
import view.CriarLista;
/**
 *
 * @author candi
 */
public class TelaListaReproducao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListaReproducao.class.getName());
    private Usuario usuario;
    /**
     * Creates new form TelaListaReproducao
     */
    public TelaListaReproducao(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_escolhaLista = new javax.swing.JLabel();
        bt_criarLista = new javax.swing.JButton();
        bt_editarLista = new javax.swing.JButton();
        bt_gerenciarVideos = new javax.swing.JButton();
        bt_excluirLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listas de Reprodução");

        lbl_escolhaLista.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_escolhaLista.setForeground(new java.awt.Color(255, 0, 153));
        lbl_escolhaLista.setText("Escolha o que você gostaria de fazer:");

        bt_criarLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_criarLista.setText("Criar uma Lista de Reprodução");
        bt_criarLista.addActionListener(this::bt_criarListaActionPerformed);

        bt_editarLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_editarLista.setText("Editar sua Lista de Reprodução");

        bt_gerenciarVideos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_gerenciarVideos.setText("Adicionar/remover vídeo");
        bt_gerenciarVideos.addActionListener(this::bt_gerenciarVideosActionPerformed);

        bt_excluirLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_excluirLista.setText("Excluir uma Lista de Reprodução");
        bt_excluirLista.addActionListener(this::bt_excluirListaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_editarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_criarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_gerenciarVideos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_excluirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_escolhaLista)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lbl_escolhaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bt_criarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_editarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_gerenciarVideos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_excluirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_gerenciarVideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerenciarVideosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_gerenciarVideosActionPerformed

    private void bt_excluirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_excluirListaActionPerformed

    private void bt_criarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criarListaActionPerformed
        // TODO add your handling code here:
        CriarLista tela8 = new CriarLista(usuario);
        tela8.setVisible(true);
    }//GEN-LAST:event_bt_criarListaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new TelaListaReproducao().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_criarLista;
    private javax.swing.JButton bt_editarLista;
    private javax.swing.JButton bt_excluirLista;
    private javax.swing.JButton bt_gerenciarVideos;
    private javax.swing.JLabel lbl_escolhaLista;
    // End of variables declaration//GEN-END:variables
}
