/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleAvaliacao;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author candi
 */
public class TelaAvaliacoes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAvaliacoes.class.getName());

    /**
     * Creates new form Avaliacoes
     */
    public TelaAvaliacoes(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null); //aparece no meio

        c = new ControleAvaliacao(this, usuario);

    }

    public ControleAvaliacao getC() {
        return c;
    }

    public void setC(ControleAvaliacao c) {
        this.c = c;
    }

    public JButton getBt_buscar() {
        return bt_buscar;
    }

    public void setBt_buscar(JButton bt_buscar) {
        this.bt_buscar = bt_buscar;
    }

    public JButton getBt_curtir() {
        return bt_curtir;
    }

    public void setBt_curtir(JButton bt_curtir) {
        this.bt_curtir = bt_curtir;
    }

    public JButton getBt_descurtir() {
        return bt_descurtir;
    }

    public void setBt_descurtir(JButton bt_descurtir) {
        this.bt_descurtir = bt_descurtir;
    }

    public JLabel getLbl_descricao() {
        return lbl_descricao;
    }

    public void setLbl_descricao(JLabel lbl_descricao) {
        this.lbl_descricao = lbl_descricao;
    }

    public JLabel getLbl_nomeVideo() {
        return lbl_nomeVideo;
    }

    public void setLbl_nomeVideo(JLabel lbl_nomeVideo) {
        this.lbl_nomeVideo = lbl_nomeVideo;
    }

    public JTextField getTxt_buscarVideo() {
        return txt_buscarVideo;
    }

    public void setTxt_buscarVideo(JTextField txt_buscarVideo) {
        this.txt_buscarVideo = txt_buscarVideo;
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nomeVideo = new javax.swing.JLabel();
        txt_buscarVideo = new javax.swing.JTextField();
        lbl_descricao = new javax.swing.JLabel();
        bt_curtir = new javax.swing.JButton();
        bt_descurtir = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nomeVideo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_nomeVideo.setText("Busque o nome do vídeo que deseja curtir/descurtir:");

        txt_buscarVideo.addActionListener(this::txt_buscarVideoActionPerformed);

        lbl_descricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_descricao.setText("  ");

        bt_curtir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_curtir.setForeground(new java.awt.Color(0, 255, 0));
        bt_curtir.setText("Curtir");
        bt_curtir.addActionListener(this::bt_curtirActionPerformed);

        bt_descurtir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_descurtir.setForeground(new java.awt.Color(255, 0, 51));
        bt_descurtir.setText("Descurtir");
        bt_descurtir.addActionListener(this::bt_descurtirActionPerformed);

        bt_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(this::bt_buscarActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_nomeVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_buscarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(bt_curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(bt_descurtir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbl_nomeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_buscarVideo)
                    .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_descurtir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_curtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtirActionPerformed
        // TODO add your handling code here:
        c.curtir();
    }//GEN-LAST:event_bt_curtirActionPerformed

    private void bt_descurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descurtirActionPerformed
        // TODO add your handling code here:
        c.descurtir();
    }//GEN-LAST:event_bt_descurtirActionPerformed

    private void txt_buscarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarVideoActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        // TODO add your handling code here:
        c.buscarIdVideo();
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Avaliacoes().setVisible(true));
//    }
    
    private ControleAvaliacao c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_curtir;
    private javax.swing.JButton bt_descurtir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_nomeVideo;
    private javax.swing.JTextField txt_buscarVideo;
    // End of variables declaration//GEN-END:variables
}
